name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # runs when you push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and push backend image
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

      # 4. Build and push frontend image
      - name: Build and Push Frontend
        run: |
          docker build \
            --build-arg FRONTEND_VITE_REACT_APP_API_BASE_URL=${{ secrets.FRONTEND_VITE_REACT_APP_API_BASE_URL }} \
            --build-arg FRONTEND_VITE_REACT_APP_SOCKET_URL=${{ secrets.FRONTEND_VITE_REACT_APP_SOCKET_URL }} \
            --build-arg FRONTEND_VITE_REACT_APP_OPENCAGE_API_KEY=${{ secrets.FRONTEND_VITE_REACT_APP_OPENCAGE_API_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend

          docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
