name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      BACKEND_TAG: ${{ steps.set-tags.outputs.BACKEND_TAG }}
      FRONTEND_TAG: ${{ steps.set-tags.outputs.FRONTEND_TAG }}

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Set commit SHA tags
      - name: Set tags
        id: set-tags
        run: |
          echo "BACKEND_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "FRONTEND_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # 4️⃣ Build and push backend image
      - name: Build and Push Backend
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/my-backend:${GITHUB_SHA::7} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:${GITHUB_SHA::7}

      # 5️⃣ Build and push frontend image
      - name: Build and Push Frontend
        run: |
          docker build --no-cache \
            --build-arg FRONTEND_VITE_REACT_APP_API_BASE_URL=${{ secrets.FRONTEND_VITE_REACT_APP_API_BASE_URL }} \
            --build-arg FRONTEND_VITE_REACT_APP_SOCKET_URL=${{ secrets.FRONTEND_VITE_REACT_APP_SOCKET_URL }} \
            --build-arg FRONTEND_VITE_REACT_APP_OPENCAGE_API_KEY=${{ secrets.FRONTEND_VITE_REACT_APP_OPENCAGE_API_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:${GITHUB_SHA::7} ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:${GITHUB_SHA::7}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ✅ Get the commit SHA tags from the previous job
            BACKEND_TAG=${{ needs.build-and-push.outputs.BACKEND_TAG }}
            FRONTEND_TAG=${{ needs.build-and-push.outputs.FRONTEND_TAG }}

            # Pull images from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:$BACKEND_TAG
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-frontend:$FRONTEND_TAG

            # Stop and remove old containers
            sudo docker rm -f backend || true
            sudo docker rm -f frontend || true

            # Run new backend container
            sudo docker run -d \
              --name backend \
              --network webnet \
              --env-file /home/ubuntu/mern-deploy/.env \
              -p 5000:5000 \
              ${{ secrets.DOCKER_USERNAME }}/my-backend:$BACKEND_TAG

            # Run new frontend container
            sudo docker run -d \
              --name frontend \
              --network webnet \
              -p 8080:80 \
              ${{ secrets.DOCKER_USERNAME }}/my-frontend:$FRONTEND_TAG
